version: ~> 1.0 # needed for imports
import: scala/scala-dev:travis/default.yml
language: scala

scala:
   - 2.12.13
   - 2.11.12
   - 2.13.4

env:
  - ADOPTOPENJDK=8
  - ADOPTOPENJDK=11

script:
- sbt "++ ${TRAVIS_SCALA_VERSION}!" test
- git diff --exit-code # check scalariform
